FROM gitlab/gitlab-runner:alpine-v13.1.1



# CMD ["run", "--user=root", "--working-directory=/home/gitlab-runner"]

RUN git config --global user.email "jadilson12@gmail.com" && \
    git config --global user.name "Jadilson Guedes"
